@startuml
actor User
participant CentralPC as "Central PC"
participant ss as "Subsystem1..n"

autonumber
User -> CentralPC : Restart
CentralPC -> ss : "Restart Subsystem1..n"
...
ss -> CentralPC : Result1..n
CentralPC --> User : Result
@enduml