@startuml
actor User
participant CentralPC as "Central PC"
participant Subsystem

autonumber
User -> CentralPC : Restart subsystem
CentralPC -> Subsystem : Restart(Subsystem)
...
Subsystem --> CentralPC : Result
CentralPC --> User : Result
@enduml