@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Error handling software architecture, Subsystem

System(central_pc, "Central PC", "", "" )

System_Boundary(subsystem_n, "Subsystem n") {
  Container(controller_n, "Embedded controller n", $link="embedded_controller.puml")
  Container_Ext(cots_n1, "COTS n.1")
  Container_Ext(cots_n2, "COTS n.2")
  Rel(controller_n, cots_n1, "Command")
  Rel(controller_n, cots_n2, "Command")
  Rel_Back(controller_n, cots_n1, "Ack")
  Rel_Back(controller_n, cots_n2, "Ack")
}

BiRel(central_pc, controller_n, "Uses")

SHOW_LEGEND()

@enduml